language: ruby
cache: bundler
rvm:
  - 2.3.0
git:
  depth: 1
addons:
  code_climate:
    repo_token: e9d8e1e9f021d0e17fc0feb71f9aebdfa15807ab32389d9549d9c219e9f34f06
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
